countries = { "Austria": "AT",
 "Belgium": "BE", 
 "Bulgaria": "BG", 
 "Croatia": "HR", 
 "Cyprus": "CY", 
 "Czechia": "CZ", 
 "Denmark": "DK", 
 "Estonia": "EE", 
 "Finland":"FI", 
 "France": "FR", 
 "Germany": "DE", 
 "Greece": "EL", 
 "Hungary": "HU", 
 "Ireland": "IE", 
 "Italy": "IT", 
 "Latvia": "LV", 
 "Lithuania": "LT", 
 "Luxembourg": "LU", 
 "Malta": "MT", 
 "Netherlands": "NL", 
 "Poland": "PL", 
 "Portugal": "PT", 
 "Romania": "RO", 
 "Slovakia": "SK", 
 "Slovenia": "SI", 
 "Spain": "ES", 
 "Sweden": "SE"}

countries_ISO3 = {'AUT': ' Austria',
 'BEL': ' Belgium',
 'BGR': ' Bulgaria',
 'HRV': ' Croatia',
 'CYP': ' Cyprus',
 'CZE': ' Czech Republic',
 'DNK': ' Denmark',
 'EST': ' Estonia',
 'FIN': ' Finland',
 'FRA': ' France',
 'DEU': ' Germany',
 'GRC': ' Greece',
 'HUN': ' Hungary',
 'IRL': ' Ireland',
 'ITA': ' Italy',
 'LVA': ' Latvia',
 'LTU': ' Lithuania',
 'LUX': ' Luxembourg',
 'MLT': ' Malta',
 'NLD': ' Netherlands',
 'POL': ' Poland',
 'PRT': ' Portugal',
 'ROU': ' Romania',
 'SVK': ' Slovakia',
 'SVN': ' Slovenia',
 'ESP': ' Spain',
 'SWE': ' Sweden'}

codes = {'AL': {'AL01': 'Veri',
  'AL02': 'Qender',
  'AL03': 'Jug',
  'ALZZ': 'Extra-Regio NUTS 2'},
 'AT': {'AT11': 'Burgenland',
  'AT12': 'Niederösterreich',
  'AT13': 'Wien',
  'AT21': 'Kärnten',
  'AT22': 'Steiermark',
  'AT31': 'Oberösterreich',
  'AT32': 'Salzburg',
  'AT33': 'Tirol',
  'AT34': 'Vorarlberg',
  'ATZZ': 'Extra-Regio NUTS 2'},
 'BE': {'BE10': 'Région de Bruxelles-Capitale/ Brussels Hoofdstedelijk Gewest',
  'BE21': 'Prov. Antwerpen',
  'BE22': 'Prov. Limburg (BE)',
  'BE23': 'Prov. Oost-Vlaanderen',
  'BE24': 'Prov. Vlaams-Brabant',
  'BE25': 'Prov. West-Vlaanderen',
  'BE31': 'Prov. Brabant Wallon',
  'BE32': 'Prov. Hainaut',
  'BE33': 'Prov. Liège',
  'BE34': 'Prov. Luxembourg (BE)',
  'BE35': 'Prov. Namur',
  'BEZZ': 'Extra-Regio NUTS 2'},
 'BG': {'BG31': 'Северозападен',
  'BG32': 'Северен централен',
  'BG33': 'Североизточен',
  'BG34': 'Югоизточен',
  'BG41': 'Югозападен',
  'BG42': 'Южен централен',
  'BGZZ': 'Extra-Regio NUTS 2'},
 'CH': {'CH01': 'Région lémanique',
  'CH02': 'Espace Mittelland',
  'CH03': 'Nordwestschweiz',
  'CH04': 'Zürich',
  'CH05': 'Ostschweiz',
  'CH06': 'Zentralschweiz',
  'CH07': 'Ticino',
  'CHZZ': 'Extra-Regio NUTS 2'},
 'CY': {'CY00': 'Κύπρος', 'CYZZ': 'Extra-Regio NUTS 2'},
 'CZ': {'CZ01': 'Praha',
  'CZ02': 'Střední Čechy',
  'CZ03': 'Jihozápad',
  'CZ04': 'Severozápad',
  'CZ05': 'Severovýchod',
  'CZ06': 'Jihovýchod',
  'CZ07': 'Střední Morava',
  'CZ08': 'Moravskoslezsko',
  'CZZZ': 'Extra-Regio NUTS 2'},
 'DE': {'DE11': 'Stuttgart',
  'DE12': 'Karlsruhe',
  'DE13': 'Freiburg',
  'DE14': 'Tübingen',
  'DE21': 'Oberbayern',
  'DE22': 'Niederbayern',
  'DE23': 'Oberpfalz',
  'DE24': 'Oberfranken',
  'DE25': 'Mittelfranken',
  'DE26': 'Unterfranken',
  'DE27': 'Schwaben',
  'DE30': 'Berlin',
  'DE40': 'Brandenburg',
  'DE50': 'Bremen',
  'DE60': 'Hamburg',
  'DE71': 'Darmstadt',
  'DE72': 'Gießen',
  'DE73': 'Kassel',
  'DE80': 'Mecklenburg-Vorpommern',
  'DE91': 'Braunschweig',
  'DE92': 'Hannover',
  'DE93': 'Lüneburg',
  'DE94': 'Weser-Ems',
  'DEA1': 'Düsseldorf',
  'DEA2': 'Köln',
  'DEA3': 'Münster',
  'DEA4': 'Detmold',
  'DEA5': 'Arnsberg',
  'DEB1': 'Koblenz',
  'DEB2': 'Trier',
  'DEB3': 'Rheinhessen-Pfalz',
  'DEC0': 'Saarland',
  'DED2': 'Dresden',
  'DED4': 'Chemnitz',
  'DED5': 'Leipzig',
  'DEE0': 'Sachsen-Anhalt',
  'DEF0': 'Schleswig-Holstein',
  'DEG0': 'Thüringen',
  'DEZZ': 'Extra-Regio NUTS 2'},
 'DK': {'DK01': 'Hovedstaden',
  'DK02': 'Sjælland',
  'DK03': 'Syddanmark',
  'DK04': 'Midtjylland',
  'DK05': 'Nordjylland',
  'DKZZ': 'Extra-Regio NUTS 2'},
 'EE': {'EE00': 'Eesti', 'EEZZ': 'Extra-Regio NUTS 2'},
 'EL': {'EL30': 'Aττική',
  'EL41': 'Βόρειο Αιγαίο',
  'EL42': 'Νότιο Αιγαίο',
  'EL43': 'Κρήτη',
  'EL51': 'Aνατολική Μακεδονία, Θράκη',
  'EL52': 'Κεντρική Μακεδονία',
  'EL53': 'Δυτική Μακεδονία',
  'EL54': 'Ήπειρος',
  'EL61': 'Θεσσαλία',
  'EL62': 'Ιόνια Νησιά',
  'EL63': 'Δυτική Ελλάδα',
  'EL64': 'Στερεά Ελλάδα',
  'EL65': 'Πελοπόννησος',
  'ELZZ': 'Extra-Regio NUTS 2'},
 'ES': {'ES11': 'Galicia',
  'ES12': 'Principado de Asturias',
  'ES13': 'Cantabria',
  'ES21': 'País Vasco',
  'ES22': 'Comunidad Foral de Navarra',
  'ES23': 'La Rioja',
  'ES24': 'Aragón',
  'ES30': 'Comunidad de Madrid',
  'ES41': 'Castilla y León',
  'ES42': 'Castilla-La Mancha',
  'ES43': 'Extremadura',
  'ES51': 'Cataluña',
  'ES52': 'Comunitat Valenciana ',
  'ES53': 'Illes Balears',
  'ES61': 'Andalucía',
  'ES62': 'Región de Murcia',
  'ES63': 'Ciudad de Ceuta',
  'ES64': 'Ciudad de Melilla',
  'ES70': 'Canarias',
  'ESZZ': 'Extra-Regio NUTS 2'},
 'FI': {'FI19': 'Länsi-Suomi',
  'FI1B': 'Helsinki-Uusimaa',
  'FI1C': 'Etelä-Suomi',
  'FI1D': 'Pohjois- ja Itä-Suomi',
  'FI20': 'Åland',
  'FIZZ': 'Extra-Regio NUTS 2'},
 'FR': {'FR10': 'Ile-de-France',
  'FRB0': 'Centre — Val de Loire',
  'FRC1': 'Bourgogne',
  'FRC2': 'Franche-Comté',
  'FRD1': 'Basse-Normandie ',
  'FRD2': 'Haute-Normandie ',
  'FRE1': 'Nord-Pas de Calais',
  'FRE2': 'Picardie',
  'FRF1': 'Alsace',
  'FRF2': 'Champagne-Ardenne',
  'FRF3': 'Lorraine',
  'FRG0': 'Pays de la Loire',
  'FRH0': 'Bretagne',
  'FRI1': 'Aquitaine',
  'FRI2': 'Limousin',
  'FRI3': 'Poitou-Charentes',
  'FRJ1': 'Languedoc-Roussillon',
  'FRJ2': 'Midi-Pyrénées',
  'FRK1': 'Auvergne',
  'FRK2': 'Rhône-Alpes',
  'FRL0': 'Provence-Alpes-Côte d’Azur',
  'FRM0': 'Corse',
  'FRY1': 'Guadeloupe',
  'FRY2': 'Martinique ',
  'FRY3': 'Guyane',
  'FRY4': 'La Réunion ',
  'FRY5': 'Mayotte',
  'FRZZ': 'Extra-Regio NUTS 2'},
 'HR': {'HR02': 'Panonska Hrvatska',
  'HR03': 'Jadranska Hrvatska',
  'HR05': 'Grad Zagreb',
  'HR06': 'Sjeverna Hrvatska',
  'HRZZ': 'Extra-Regio NUTS 2'},
 'HU': {'HU11': 'Budapest',
  'HU12': 'Pest',
  'HU21': 'Közép-Dunántúl',
  'HU22': 'Nyugat-Dunántúl',
  'HU23': 'Dél-Dunántúl',
  'HU31': 'Észak-Magyarország',
  'HU32': 'Észak-Alföld',
  'HU33': 'Dél-Alföld',
  'HUZZ': 'Extra-Regio NUTS 2'},
 'IE': {'IE04': 'Northern and Western',
  'IE05': 'Southern',
  'IE06': 'Eastern and Midland',
  'IEZZ': 'Extra-Regio NUTS 2'},
 'IS': {'IS00': 'Ísland', 'ISZZ': 'Extra-Regio NUTS 2'},
 'IT': {'ITC1': 'Piemonte',
  'ITC2': 'Valle d’Aosta/Vallée d’Aoste',
  'ITC3': 'Liguria',
  'ITC4': 'Lombardia',
  'ITF1': 'Abruzzo',
  'ITF2': 'Molise',
  'ITF3': 'Campania',
  'ITF4': 'Puglia',
  'ITF5': 'Basilicata',
  'ITF6': 'Calabria',
  'ITG1': 'Sicilia',
  'ITG2': 'Sardegna',
  'ITH1': 'Provincia Autonoma di Bolzano/Bozen',
  'ITH2': 'Provincia Autonoma di Trento',
  'ITH3': 'Veneto',
  'ITH4': 'Friuli-Venezia Giulia',
  'ITH5': 'Emilia-Romagna',
  'ITI1': 'Toscana',
  'ITI2': 'Umbria',
  'ITI3': 'Marche',
  'ITI4': 'Lazio',
  'ITZZ': 'Extra-Regio NUTS 2'},
 'LI': {'LI00': 'Liechtenstein', 'LIZZ': 'Extra-Regio NUTS 2'},
 'LT': {'LT01': 'Sostinės regionas',
  'LT02': 'Vidurio ir vakarų Lietuvos regionas ',
  'LTZZ': 'Extra-Regio NUTS 2'},
 'LU': {'LU00': 'Luxembourg', 'LUZZ': 'Extra-Regio NUTS 2'},
 'LV': {'LV00': 'Latvija', 'LVZZ': 'Extra-Regio NUTS 2'},
 'ME': {'ME00': 'Црна Гора', 'MEZZ': 'Extra-Regio NUTS 2'},
 'MK': {'MK00': 'Северна Македонија', 'MKZZ': 'Extra-Regio NUTS 2'},
 'MT': {'MT00': 'Malta', 'MTZZ': 'Extra-Regio NUTS 2'},
 'NL': {'NL11': 'Groningen',
  'NL12': 'Friesland (NL)',
  'NL13': 'Drenthe',
  'NL21': 'Overijssel',
  'NL22': 'Gelderland',
  'NL23': 'Flevoland',
  'NL31': 'Utrecht',
  'NL32': 'Noord-Holland',
  'NL33': 'Zuid-Holland',
  'NL34': 'Zeeland',
  'NL41': 'Noord-Brabant',
  'NL42': 'Limburg (NL)',
  'NLZZ': 'Extra-Regio NUTS 2'},
 'NO': {'NO02': 'Innlandet',
  'NO06': 'Trøndelag',
  'NO07': 'Nord-Norge',
  'NO08': 'Oslo og Viken',
  'NO09': 'Agder og Sør-Østlandet',
  'NO0A': 'Vestlandet',
  'NO0B': 'Jan Mayen and Svalbard',
  'NOZZ': 'Extra-Regio NUTS 2'},
 'PL': {'PL21': 'Małopolskie',
  'PL22': 'Śląskie',
  'PL41': 'Wielkopolskie',
  'PL42': 'Zachodniopomorskie',
  'PL43': 'Lubuskie',
  'PL51': 'Dolnośląskie',
  'PL52': 'Opolskie',
  'PL61': 'Kujawsko-pomorskie',
  'PL62': 'Warmińsko-mazurskie',
  'PL63': 'Pomorskie',
  'PL71': 'Łódzkie',
  'PL72': 'Świętokrzyskie',
  'PL81': 'Lubelskie',
  'PL82': 'Podkarpackie',
  'PL84': 'Podlaskie',
  'PL91': 'Warszawski stołeczny',
  'PL92': 'Mazowiecki regionalny',
  'PLZZ': 'Extra-Regio NUTS 2'},
 'PT': {'PT11': 'Norte',
  'PT15': 'Algarve',
  'PT16': 'Centro (PT)',
  'PT17': 'Área Metropolitana de Lisboa',
  'PT18': 'Alentejo',
  'PT20': 'Região Autónoma dos Açores',
  'PT30': 'Região Autónoma da Madeira',
  'PTZZ': 'Extra-Regio NUTS 2'},
 'RO': {'RO11': 'Nord-Vest',
  'RO12': 'Centru',
  'RO21': 'Nord-Est',
  'RO22': 'Sud-Est',
  'RO31': 'Sud-Muntenia',
  'RO32': 'Bucureşti-Ilfov',
  'RO41': 'Sud-Vest Oltenia',
  'RO42': 'Vest',
  'ROZZ': 'Extra-Regio NUTS 2'},
 'RS': {'RS11': 'Београдски регион',
  'RS12': 'Регион Војводине',
  'RS21': 'Регион Шумадије и Западне Србије',
  'RS22': 'Регион Јужне и Источне Србије',
  'RSZZ': 'Extra-Regio NUTS 2'},
 'SE': {'SE11': 'Stockholm',
  'SE12': 'Östra Mellansverige',
  'SE21': 'Småland med öarna',
  'SE22': 'Sydsverige',
  'SE23': 'Västsverige',
  'SE31': 'Norra Mellansverige',
  'SE32': 'Mellersta Norrland',
  'SE33': 'Övre Norrland',
  'SEZZ': 'Extra-Regio NUTS 2'},
 'SI': {'SI03': 'Vzhodna Slovenija',
  'SI04': 'Zahodna Slovenija',
  'SIZZ': 'Extra-Regio NUTS 2'},
 'SK': {'SK01': 'Bratislavský kraj',
  'SK02': 'Západné Slovensko',
  'SK03': 'Stredné Slovensko',
  'SK04': 'Východné Slovensko',
  'SKZZ': 'Extra-Regio NUTS 2'},
 'TR': {'TR10 ': 'İstanbul',
  'TR21': 'Tekirdağ, Edirne, Kırklareli',
  'TR22': 'Balıkesir, Çanakkale',
  'TR31': 'İzmir',
  'TR32': 'Aydın, Denizli, Muğla',
  'TR33': 'Manisa, Afyonkarahisar, Kütahya, Uşak',
  'TR41': 'Bursa, Eskişehir, Bilecik',
  'TR42': 'Kocaeli, Sakarya, Düzce, Bolu, Yalova',
  'TR51': 'Ankara',
  'TR52': 'Konya, Karaman',
  'TR61': 'Antalya, Isparta, Burdur',
  'TR62': 'Adana, Mersin',
  'TR63': 'Hatay, Kahramanmaraş, Osmaniye',
  'TR71': 'Kırıkkale, Aksaray, Niğde, Nevşehir, Kırşehir',
  'TR72': 'Kayseri, Sivas, Yozgat',
  'TR81': 'Zonguldak, Karabük, Bartın',
  'TR82': 'Kastamonu, Çankırı, Sinop',
  'TR83': 'Samsun, Tokat, Çorum, Amasya',
  'TR90 ': 'Trabzon, Ordu, Giresun, Rize, Artvin, Gümüşhane',
  'TRA1': 'Erzurum, Erzincan, Bayburt',
  'TRA2': 'Ağrı, Kars, Iğdır, Ardahan',
  'TRB1': 'Malatya, Elazığ, Bingöl, Tunceli',
  'TRB2': 'Van, Muş, Bitlis, Hakkari',
  'TRC1': 'Gaziantep, Adıyaman, Kilis',
  'TRC2': 'Şanlıurfa, Diyarbakır',
  'TRC3': 'Mardin, Batman, Şırnak, Siirt',
  'TRZZ': 'Extra-Regio NUTS 2'},
 'UK': {'UKC1': 'Tees Valley and Durham',
  'UKC2': 'Northumberland and Tyne and Wear',
  'UKD1': 'Cumbria',
  'UKD3': 'Greater Manchester',
  'UKD4': 'Lancashire',
  'UKD6': 'Cheshire',
  'UKD7': 'Merseyside',
  'UKE1': 'East Yorkshire and Northern Lincolnshire',
  'UKE2': 'North Yorkshire',
  'UKE3': 'South Yorkshire',
  'UKE4': 'West Yorkshire',
  'UKF1': 'Derbyshire and Nottinghamshire',
  'UKF2': 'Leicestershire, Rutland and Northamptonshire',
  'UKF3': 'Lincolnshire',
  'UKG1': 'Herefordshire, Worcestershire and Warwickshire',
  'UKG2': 'Shropshire and Staffordshire',
  'UKG3': 'West Midlands',
  'UKH1': 'East Anglia',
  'UKH2': 'Bedfordshire and Hertfordshire',
  'UKH3': 'Essex',
  'UKI3': 'Inner London — West',
  'UKI4': 'Inner London — East',
  'UKI5': 'Outer London — East and North East',
  'UKI6': 'Outer London — South',
  'UKI7': 'Outer London — West and North West',
  'UKJ1': 'Berkshire, Buckinghamshire and Oxfordshire',
  'UKJ2': 'Surrey, East and West Sussex',
  'UKJ3': 'Hampshire and Isle of Wight',
  'UKJ4': 'Kent',
  'UKK1': 'Gloucestershire, Wiltshire and Bristol/Bath area',
  'UKK2': 'Dorset and Somerset',
  'UKK3': 'Cornwall and Isles of Scilly',
  'UKK4': 'Devon',
  'UKL1': 'West Wales and The Valleys',
  'UKL2': 'East Wales',
  'UKM5': 'North Eastern Scotland',
  'UKM6': 'Highlands and Islands',
  'UKM7': 'Eastern Scotland',
  'UKM8': 'West Central Scotland',
  'UKM9': 'Southern Scotland',
  'UKN0': 'Northern Ireland',
  'UKZZ': 'Extra-Regio NUTS 2'}}